### ISSUE TITLE
x64?

### ISSUE THREAD

**Issue by filipovskis** [danielga/gm_spew#2]
How I can build it in x64?

When I'm trying to do that using project generator v3 it gives me errors.
![изображение](https://user-images.githubusercontent.com/48033052/104336139-c5165900-54fc-11eb-9f8a-4b149f1fa494.png)

**Comment by danielga** [comment]
Even if I fixed whatever is broken in x86-64 builds, it wouldn't work on the x86-64 branch of Garry's Mod. This uses an interface that doesn't exist on that branch.
